[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["kernel"]

[dependencies]
ovmf-prebuilt = "0.1.0-alpha.1"
bootloader = "0.11.7"
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
wait-timeout = "0.2.0"
serial_test = "3.1.1"
