name: Main

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [stable, beta, nightly]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - name: Install rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
      - run: cargo test --verbose

  integration-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: testing
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Qemu
        run: |
          sudo apt update
          sudo apt install qemu-system
      - name: Install Rust
        run: |
          rustup update nightly --no-self-update
          rustup default nightly
          rustup target add x86_64-unknown-none
          rustup component add rust-src
          rustup component add llvm-tools-preview
      - run: cargo test --verbose

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install rust
        run: |
          rustup update stable --no-self-update
          rustup default stable
      - run: cargo fmt -- --check
